//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDetalle
    {
        public int CodigoOrdenDetalle { get; set; }
        public int CodigoOrden { get; set; }
        public int CodigoProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Costo { get; set; }
        public decimal PrecioVenta { get; set; }
        public int CodigoEstado { get; set; }
        public Nullable<bool> Borrado { get; set; }
    
        public virtual Estado Estados { get; set; }
        public virtual Orden Ordenes { get; set; }
        public virtual Producto Productos { get; set; }
    }
}
